### ISSUE TITLE
How to support time-shift function in live broadcast?

### ISSUE THREAD

**Issue by TimLuminesence** [aws-samples/amazon-ivs-auto-record-to-s3-web-demo#3]
Tried this code. It works well for live broadcast and see VOD content stored at S3.
We want to support time-shift function in live broadcast. Our SA told us to "IVS R2S3+ Amazon S3 Object Lambda delete #EXT-X-ENDLIST". 
How can we do that in this demo? 
Thanks!

**Comment by slee-aws** [comment]
Hi there! That functionality is not the focus of this demo and we unfortunately do not have sample code to share for that use-case at this time.

I have not yet explored how to build such a feature, but I think a time-shift function could be built with the following modifications to this demo. **This is not guaranteed to work, and I haven't tried it myself**:
1. Add a listener for the "Recording Start" event in `stream-state-change-event.js`. When this event is received, you can retrieve some information about the playlist, such as the [VOD Playback URL](https://github.com/aws-samples/amazon-ivs-auto-record-to-s3-web-demo/blob/main/serverless/lambda/stream-state-change-event.js#L44) or [thumbnails](https://github.com/aws-samples/amazon-ivs-auto-record-to-s3-web-demo/blob/main/serverless/lambda/stream-state-change-event.js#L48).
2. Based on what you mentioned about deleting `#EXT-X-ENDLIST`, you may need to continuously delete that value from the `playlist.m3u8` files that are generated in S3. These files will be in a subfolder that looks like `.../media/hls/720p60/`. I'm not completely sure how the person you spoke with proposed to do this, so you may need to follow up with them to confirm the method, or check if this step is necessary.
3. Use the Amazon IVS player to load the playlist file that you logged from the "Recording Start" event. You will need to build some logic in the client app that will replace the `playbackUrl` prop in [`Home.jsx`](https://github.com/aws-samples/amazon-ivs-auto-record-to-s3-web-demo/blob/main/web-ui/src/pages/Home.jsx#L84) with the playlist file you want to load. For example, this could be triggered by a button, so that when the user clicks a button in the UI, you toggle between the VOD playlist and the live stream.

I am unfortunately unable to provide further support on this feature and since this is not currently the focus of this demo, I will close this issue. If you have additional questions on this topic, you can reply to this issue and I will help if I am able to.
